services:
  mongodb:
    container_name: mongodb
    #image: mongo:latest
    image: mongo:4.4.29 # This is due to limitations in the Virtual Wall's hardware
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo-data:/data/db
    # Don't expose the port to the outside world when running publicly
    #ports:
    #  - 27017:27017
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - ldes
  ldes-server:
    build: ./ldes-server
    ports:
      - 80:3000
    restart: always
    command: -b http://semic.ilabt.imec.be
    healthcheck:
      test: wget --spider -q http://semic.ilabt.imec.be/sweden/default || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - ldes
    depends_on:
      - mongodb
  sweden-feed-pipeline:
    container_name: sweden-feed-pipeline
    build:
      context: .
      dockerfile: ./sweden/Dockerfile-feed
    environment:
      - DEBUG=*
    volumes:
      - ./leveldb:/opt/pipeline/leveldb
      - ./feed-state:/opt/pipeline/feed-state
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - ldes
    depends_on:
      - mongodb
  sweden-validation-pipeline:
    container_name: sweden-validation-pipeline
    build:
      context: .
      dockerfile: ./sweden/Dockerfile-validation
    environment:
      - DEBUG=*
    volumes:
      - ./validation-state:/opt/pipeline/validation-state
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - ldes
    depends_on:
      ldes-server:
        condition: service_healthy
      mongodb:
        condition: service_started

networks:
  ldes:
    name: ldes-network
