services:
  mongodb:
    container_name: mongodb
    #image: mongo:latest
    image: mongo:4.4.29 # This is due to limitations in the Virtual Wall's hardware
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo-data:/data/db
    # Don't expose the port to the outside world when running publicly
    #ports:
    #  - 27017:27017
    restart: always
    networks:
      - ldes
  ldes-server:
    build: ./ldes-server
    ports:
      - 3000:3000
    restart: always
    command: -b http://semic.ilabt.imec.be:3000
    networks:
      - ldes
    depends_on:
      - mongodb
  sweden-feed-pipeline:
    container_name: sweden-feed-pipeline
    build:
      context: .
      dockerfile: ./sweden/Dockerfile-feed
    networks:
      - ldes
    depends_on:
      - mongodb
  sweden-validation-pipeline:
    container_name: sweden-validation-pipeline
    build:
      context: .
      dockerfile: ./sweden/Dockerfile-validation
    networks:
      - ldes
    depends_on:
      - mongodb
      - ldes-server

networks:
  ldes:
    name: ldes-network
