# Start from a Bun ready container
FROM node:lts-alpine

# Setup working folder
WORKDIR /opt/pipeline
COPY . .

# Install dependencies
RUN npm install

# Container's entrypoint command
ENTRYPOINT [ "npx", "js-runner", "sweden/dumps-to-feed-pipeline.ttl" ]
